# Generated by Django 2.0.13 on 2019-03-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20190321_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='avg_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
