# Generated by Django 2.0.13 on 2019-03-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_candidate_avg_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='candidate',
        ),
        migrations.AddField(
            model_name='candidate',
            name='grades',
            field=models.ManyToManyField(to='quickstart.Grade'),
        ),
    ]
