# Generated by Django 2.0.13 on 2019-03-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20190321_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='avg_grade',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='grades',
        ),
        migrations.AddField(
            model_name='grade',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Candidate'),
            preserve_default=False,
        ),
    ]
