# Generated by Django 2.0.13 on 2019-03-21 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20190321_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Candidate')),
                ('grades', models.ManyToManyField(to='quickstart.Grade')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Task')),
            ],
        ),
    ]
