# Generated by Django 2.0.13 on 2019-03-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_allabout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allabout',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='allabout',
            name='task',
        ),
    ]
