# Generated by Django 2.0.13 on 2019-03-22 14:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20190322_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='allabout',
            name='grades',
            field=models.ManyToManyField(to='quickstart.Grade'),
        ),
        migrations.AddField(
            model_name='allabout',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(2)]),
        ),
    ]
