# Generated by Django 2.0.13 on 2019-03-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
